// Package skipgenerated is skip analysis file that begin with comment "Code generated by ".
package skipgenerated

import (
	"go/ast"
	"strings"

	"golang.org/x/tools/go/analysis"
)

const codeGeneratedBy = "// Code generated by "

func WrapList(analyzers []*analysis.Analyzer) {
	for _, a := range analyzers {
		Wrap(a)
	}
}

func Wrap(analyzer *analysis.Analyzer) {
	run := analyzer.Run

	analyzer.Run = func(p *analysis.Pass) (interface{}, error) {
		var notGeneratedFiles []*ast.File

		for _, file := range p.Files {
			if len(file.Comments) == 0 {
				notGeneratedFiles = append(notGeneratedFiles, file)
				continue
			}

			if len(file.Comments[0].List) > 0 && !strings.HasPrefix(file.Comments[0].List[0].Text, codeGeneratedBy) {
				notGeneratedFiles = append(notGeneratedFiles, file)
			}
		}

		p.Files = notGeneratedFiles

		return run(p)
	}
}
