name: go test cover

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cover:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test cover
        run: make cover
