name: staticlint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        run: |
          go run cmd/staticlint/main.go ./...
